pipeline {
    agent any

    parameters {
        string(name: 'TAG', defaultValue: "AddPlace", description: 'Enter the tag you want to use for execution')
    }

    stages {
        stage('GIT Checkout') {
            steps {
                echo "*********Git checkout code*********"
                git branch: 'develop',
                        credentialsId: 'GitHub_643',
                        url: 'https://github.com/vdinuu/BDD_APIAutomationFramework.git'
            }
        }
        stage('Execute test cases') {
            steps {
                echo "*********Executing test cases**********"
                bat """
                    mvn clean test "-Dcucumber.filter.tags=@${params.TAG}"
                    """
            }
        }
        stage('Generate HTML Report') {
            steps {
                echo "*********Generating HTML report*********"
                bat 'allure generate allure-results'
            }
        }
        //Make sure to install HTML publisher plugin before using this stage
        stage('Publish HTML report') {
            steps {
                publishHTML(target: [
                        reportName: 'API Test Execution report', // Name of the report
                        reportDir: 'allure-report',          // Directory containing the HTML report
                        reportFiles: 'index.html',   // The specific HTML file to publish
                        keepAll: true,                // Keeps all previous reports (optional)
                        alwaysLinkToLastBuild: true   // Always link to the last build (optional)
                ])
            }
        }
    }
}