pipeline {
    agent any

    parameters {
        string(name: 'TAG', defaultValue: "AddPlace", description: 'Enter the tag you want to use for execution')
    }

    stages {
        stage('GIT Checkout') {
            steps {
                git branch: 'develop',
                        credentialsId: 'GitHub_643',
                        url: 'https://github.com/vdinuu/BDD_APIAutomationFramework.git'
            }
        }
        stage('Execute test cases') {
            steps {
                bat 'mvn clean test "-Dcucumber.filter.tags=@${params.TAG}"'
            }
        }
    }
}